### ISSUE TITLE
Where to find the color UI component? 

### ISSUE THREAD

**Issue by yiyaonie** [jetstyle/Apple-Vision-Pro-UI-Kit#4]
Hello, thank you for providing this useful toolkit. From the readme, there is color UI component. But I don't see this one in the package. Wondering where can I find it? Thanks.

**Comment by AlexNashZemlyak** [comment]
Hello, i'm afraid this is misunderstanding: colorpicker **as a component** does not present in the kit, but you can assemble one, using other smaller components from the kit
