### ISSUE TITLE
window become gary in AppleVisionPro

### ISSUE THREAD

**Issue by chaoslife** [jetstyle/Apple-Vision-Pro-UI-Kit#5]
Hi, 
I created a new window and the effect was right in UnityEditor. When packaged into AVP, the window turned gray and had no blur effect, including other UIs that were different from those displayed in the Editor.

Did I forget to set it somewhere?

**Comment by chaoslife** [comment]
my app mode is MR - volume

**Comment by ariestav** [comment]
@chaoslife When I go to "File > Run and Build..." everything seems to get built without errors, but all bitmaps (PNG) shaders,  and even the environment do not seems to render at all.  All I see is a gray background.  Did you manage to get the demo to work?

**Comment by chaoslife** [comment]
> @chaoslife When I go to "File > Run and Build..." everything seems to get built without errors, but all bitmaps (PNG) shaders, and even the environment do not seems to render at all. All I see is a gray background. Did you manage to get the demo to work?

I can build successfully and run it in AVP, but the semi-transparent material of the UI is not supported and becomes opaque.

**Comment by JetNik** [comment]
Hello, this package is for **prototyping Vision Pro interfaces** on other devices (Quest 2, Quest Pro, Quest 3). Our shaders do not work on Vision Pro device.
I recommend you to use Unity's Polyspatial package together with Apple's SwiftUI (the Polyspatal package samples have an example of linking SwiftUI with Unity) to achieve an interface like in Vision Pro system apps.
Maybe in the future we can modify our shaders to work on Vision Pro, but for now the Polyspatial package has some shader issues.

**Comment by chaoslife** [comment]
> Hello, this package is for **prototyping Vision Pro interfaces** on other devices (Quest 2, Quest Pro, Quest 3). Our shaders do not work on Vision Pro device. I recommend you to use Unity's Polyspatial package together with Apple's SwiftUI (the Polyspatal package samples have an example of linking SwiftUI with Unity) to achieve an interface like in Vision Pro system apps. Maybe in the future we can modify our shaders to work on Vision Pro, but for now the Polyspatial package has some shader issues.

thanks reply

**Comment by ariestav** [comment]
@JetNik I still cannot get the shaders to work within Unity editor or player.  I understand that this is about getting a prototype of a Vision Pro in a Quest.  It makes sense.  However, when I open in Unity, none of the textures nor the environment is showing.  I have downloaded the repository for this along with the demo file.  You can see from my attached image, that nothing is showing up.  Any thoughts?

I do not know how to go about addressing error you see in the screenshot, but don't know if that's the answer to the issue of the textures / bitmaps (PNGs) not showing in the Unity editor or the player.  Any tips?

<img width="1105" alt="Screenshot 2024-03-18 at 1 06 12 PM" src="https://github.com/jetstyle/Apple-Vision-Pro-UI-Kit/assets/1365971/5bcf3b5e-6a51-4c9f-90d1-33b08c36913f">

**Comment by JetNik** [comment]
Let's continue in your issue in the demo scene repository at this [link](https://github.com/jetstyle/Apple-Vision-Pro-UI-Kit-Demo/issues/3), I gave you an answer in that issue.

What about your error in the console: from a question in another repository, I understand that you are using macOS, and this error says that the Oculus XR Plugin needs DirectX11, which is only available in Windows settings. This means you probably can't build the same demo on macOS.

> @JetNik I still cannot get the shaders to work within Unity editor or player. I understand that this is about getting a prototype of a Vision Pro in a Quest. It makes sense. However, when I open in Unity, none of the textures nor the environment is showing. I have downloaded the repository for this along with the demo file. You can see from my attached image, that nothing is showing up. Any thoughts?
> 
> I do not know how to go about addressing error you see in the screenshot, but don't know if that's the answer to the issue of the textures / bitmaps (PNGs) not showing in the Unity editor or the player. Any tips?
> 
> <img alt="Screenshot 2024-03-18 at 1 06 12 PM" width="1105" src="https://private-user-images.githubusercontent.com/1365971/313774062-5bcf3b5e-6a51-4c9f-90d1-33b08c36913f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDM4NzYsIm5iZiI6MTcxMDg0MzU3NiwicGF0aCI6Ii8xMzY1OTcxLzMxMzc3NDA2Mi01YmNmM2I1ZS02YTUxLTRjOWYtOTBkMS0zM2IwOGMzNjkxM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTlUMTAxOTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTQxYWVhOGQxZTc0MGI5YmQxMGRlYzAyODRmM2UzYzc3NTRmZjBkNmMxNjUzMjFmMDcxY2FlN2JjYWQyMGQ3MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QfCt8yHW232lM0_oDBKy3vuTK4QEsVgPA5fqL9kvSrQ">

**Comment by ariestav** [comment]
@JetNik Ah!  So it is thus a macOS issue, I may be able to try and build on a Windows system.  I figured that if you are building a prototyping tool for an Apple device (Vision Pro) that it would work on Unity running on macOS.  I will try Windows and report back when I find out more.  Thank you for your time.
